### PR TITLE
Allow setting a seed to always generate same data

### PR DESCRIPTION
**Pull request by utillity**
Hi,

in my opinion the need to use the Cryptographic random number generator is not needed, explicitly because if you want to always create the same data, you need to be able to set the Seed to a constant value. My change should be completely transparent and backward compatible to any users which do not need to set a constant seed.

I also added the corresponding tests.

The only change you must undo is the one to the .nuspec

Best, Tilli

### CODE REVIEW

**Comment by utillity** [comment]
As specified above: The only change you must undo is the one to the .nuspec

**Comment by oriches** [comment]
The rrandom function is designed to be random, not pseudo random clas from .Net.

**Comment by utillity** [comment]
If you search for "seeding a database with unit-test data" you will find that there are numerous tools out there which do this deterministic seeding. So there is a need for it and your tool could do both. But as I released my version to nuget as Faker.Net-Seed, I leave it up to you if you wish to also support this scenario, or if you think that just because you don't need it, noone will.

**Comment by Siliconrob** [comment]
I agree with @oriches  here.  If you want a consistent value for an input that seems like the case for a `mock` not random data as this was built to be a fairly robust random function

**Pull request closed without merging**
