### PR TITLE
updated xNumber methods

### PR DESCRIPTION
**Pull request by JosephAmalfitanoSSA**

### CODE REVIEW

**Comment by Siliconrob** [comment]
Update the README to reflect your changes as well please since it's a breaking change please

**Comment by JosephAmalfitanoSSA** [comment]
@Siliconrob not sure what you mean ---- my change was only an update to the readme since it was not accurate as it was (at least per the version I downloaded from NuGet 1.15.126)

**Comment by oriches** [comment]
This is my fault, will update read.me later today - forgot there were breaking changes, sorry.OllieOn 12 Apr 2021 03:35, Joseph Amalfitano ***@***.***> wrote:
@Siliconrob not sure what you mean ---- my change was only an update to the readme since it was not accurate as it was (at least per the version I downloaded from NuGet 1.15.126)

**Comment by Siliconrob** [comment]
My mistake, this is good

**Pull request merged**
